import urllib.request, json

req = urllib.request.Request('http://localhost:8000/api/learner/learner_002/diagnose', data=b'', method='POST')
r = urllib.request.urlopen(req)
d = json.loads(r.read())
p = d['profile']

print('=== XueQing Diagnosis Agent v2.1 ===')
print()
print(f"Learner: {p['learner']['name']} ({p['learner']['education']['level']}/{p['learner']['education']['major']})")
print(f"Profile: {p['profile_id']}  |  version: {p['profile_version']}")
print()
print(f"[learning_scope] chapter: {p['learning_scope']['chapter_id']} / {p['learning_scope']['primary_kp_name']} / {p['learning_scope']['target_depth']}")
print(f"[knowledge_mastery] theta={p['knowledge_mastery']['global_theta']}, level={p['knowledge_mastery']['ability_level']}")
print(f"[knowledge_mastery] points: {len(p['knowledge_mastery']['points'])}, domains: {list(p['knowledge_mastery']['domain_summary'].keys())}")
print(f"[ability_level] overall={p['ability_level']['overall']}, sub_dims={list(p['ability_level']['sub_dimensions'].keys())}")
print(f"[error_patterns] primary={p['error_patterns']['primary_weakness']}({p['error_patterns']['primary_weakness_ratio']:.0%}), items={len(p['error_patterns']['items'])}")
print(f"[learning_preferences] groups={list(p['learning_preferences'].keys())}")
high = sum(1 for g in p['knowledge_gaps'] if g['priority']=='high')
med = sum(1 for g in p['knowledge_gaps'] if g['priority']=='medium')
low = sum(1 for g in p['knowledge_gaps'] if g['priority']=='low')
print(f"[knowledge_gaps] total={len(p['knowledge_gaps'])} (high={high} / medium={med} / low={low})")
print(f"[depth_labels] count={len(p['depth_labels'])}")
print(f"[resource_generation_hints] scope={p['resource_generation_hints']['scope']}, chapter={p['resource_generation_hints']['target_chapter_id']}")
print(f"[prior_chapters] completed={len(p['prior_chapters'])}")
print(f"[evidence] count={len(p['evidence'])}")
print(f"[diagnosis_summary] short={p['diagnosis_summary']['short'][:50]}...")
print(f"[meta] tests={p['meta']['total_test_count']}, interactions={p['meta']['total_interaction_count']}")
print()
print("=== ALL 14 FIELDS VERIFIED ===")
